# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all devcontainers updates together
    groups:
      devcontainers:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    # Group all python updates together
    groups:
      pip:
        patterns:
          - "*"
    ignore:
      # Dependabot should not update Home Assistant as that should match the homeassistant key in hacs.json
      - dependency-name: "homeassistant"
