name: 🧹 Lint with Ruff

on:
  pull_request:
    branches:
      - main

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff
          pip install .

      - name: Lint with Ruff
        run: ruff check --output-format=github custom_components
