name: Zip Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release openmotics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Check out the code
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6

        # Step 2: Create a ZIP archive of the component directory
      - name: 📦 Create zipped release package
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/openmotics"
          zip openmotics.zip -r ./

      # Step 3: Upload ZIP as a release asset (for HACS)
      - name: ⬆️ Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/openmotics/openmotics.zip
